name: Basic Workflow
on: push
jobs:
  deploy-in-one-job:
    runs-on: ubuntu-latest

    steps:
    - name: Get the code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm ci
    - name: Run linting
      run: npm run lint
    - name: Run tests
      run: npm test
    - name: Build code
      run: npm run build
    - name: Deploy code
      run: echo "Deploying code..."
