name: Deployment in multiple jobs
on: push
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - name: Get the code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm ci
    - name: Run linting
      run: npm run lint

  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Get the code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm test

  building:
    runs-on: ubuntu-latest
    steps:
    - name: Get the code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm ci
    - name: Build code
      run: npm run build
    - name: Deploy code
      run: echo "Deploying code..."
